DROP DATABASE IF EXISTS pointback;
CREATE DATABASE pointback;
USE pointback;

CREATE TABLE produto (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Modelo VARCHAR(100) NOT NULL,
  Marca VARCHAR(100) DEFAULT NULL,  
  pontos INT DEFAULT NULL,           
  valor DECIMAL(10, 2) DEFAULT NULL  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE usuario (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,        
  cpf VARCHAR(14) NOT NULL UNIQUE, 
  dt_Nasc DATE DEFAULT NULL,
  email VARCHAR(50) NOT NULL,
  senha CHAR(60) DEFAULT NULL,
  pontos INT DEFAULT 0,
  tipo VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pedido (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  id_Comprador INT NOT NULL,
  id_Vendedor INT NOT NULL,
  id_Produto INT NOT NULL,
  valor DECIMAL(10, 2) DEFAULT NULL,
  valor_Pontos INT DEFAULT NULL,
  dt_Pedido DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (id_comprador) REFERENCES usuarios(ID),
  FOREIGN KEY (id_vendedor) REFERENCES usuarios(ID),
  FOREIGN KEY (id_produto) REFERENCES produtos(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

select * from  `usuarios`;