DROP DATABASE IF EXISTS pointback;
CREATE DATABASE pointback;
USE pointback;

CREATE TABLE produtos (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Modelo VARCHAR(100) NOT NULL,
  Marca VARCHAR(100) DEFAULT NULL,  
  pontos INT DEFAULT NULL,           
  valor DECIMAL(10, 2) DEFAULT NULL  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE usuarios (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,        
  cpf VARCHAR(14) NOT NULL UNIQUE, 
  dt_Nasc DATE DEFAULT NULL,
  email VARCHAR(50) NOT NULL,
  senha CHAR(60) DEFAULT NULL,
  pontos INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

select * from  `usuarios`;